### ISSUE TITLE
Call to pcopt.optimize() with PyOpenCL installed throws (unimportant?) error

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#22]
Running `pyebsdindex.pcopt.optimize()` after installing PyEBSDIndex with PyOpenCL (`pip install pyebsdindex[gpu]`) throws an error which apparently has no effect on the results. Using the included dynamically simulated Al pattern of shape (100, 120) and providing the PC used to create the pattern:

```python
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> from pyebsdindex import ebsd_index, pcopt
>>> pattern = plt.imread("/home/hakon/al_sim_20kv.png")
>>> plt.figure()
>>> plt.imshow(pattern, cmap="gray")
>>> indexer = ebsd_index.EBSDIndexer(vendor="EDAX", patDim=pattern.shape)
>>> pc = pcopt.optimize(pattern.reshape((1,) + pattern.shape), indexer, PC0=[0.4, 0.6, 0.5])
[Errno 2] Fila eller mappa finnes ikke: '/home/hakon/miniconda3/envs/kp-rel/lib/python3.9/site-packages/pyebsdindex/opencl/clkernels.cl'
'NoneType' object has no attribute 'radonSum'
>>> print(pc)
0.39558783 0.60637312 0.50082604]
```

![al_sim_20kv](https://user-images.githubusercontent.com/12139781/174309821-ba842692-baf4-4518-936b-7068af050a28.png)

The error message is part Norwegian ("Fila eller mappa finnes ikke") and translates to "The file or directory does not exist".

The PC seems to be optimized fine, so I won't consider this a bug. But we should make sure the error isn't displayed anyway.

**Comment by hakonanes** [comment]
The error message is displayed also when calling `EBSDIndexer.index_pats()`.

**Comment by drowenhorst-nrl** [comment]
Yeah - so our PyPI distro is not putting the "pyebsdindex/opencl/clkernels.cl" in the package.  I don't understand why.  setup.py is set to include "*.cl", and even though is it in a subdirectory, all the *.py files from that directory are included.  Any thoughts?

**Comment by drowenhorst-nrl** [comment]
At least we know that we fall back to the CPU relatively gracefully.

**Comment by drowenhorst-nrl** [comment]
Like to hear your thoughts - it looks to me like the *py files in the subdirectories are being caught by the setuptools.find_packages() function.  However, this does not catch the *.cl files.  The original layout had the cl files in the parent directory, so then they were caught by the package_data = {"pyebsdindex": [  "*.py","*.cl"] }.  However, now that I moved them out of the parent directory, they are not found.  
It appears to me that there are two options:
1 - hard code in the package_data to look for cl files in the opencl subdirectory like
` package_data = {"pyebsdindex": [  "*.py","opencl/*.cl"] }`
2 - don't use the package_data field, and instead set up a MANIFEST.in file that catches the cl files (looks like you could do a recursive search this way) and also use that to include the test pattern as well.  This appears to be the more standard method now?  
https://stackoverflow.com/questions/56688232/including-non-python-files-in-a-python-package
