### ISSUE TITLE
EMsoft PC requirement of four parameters (including pixel size)

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#32]
Hi @drowenhorst-nrl,

I see that passing the EMsoft PC requires four numbers, including the pixel size:

https://github.com/USNavalResearchLaboratory/PyEBSDIndex/blob/09da593a0559fd09b436a6600297264011e3bb96/pyebsdindex/radon_fast.py#L260-L266

Might it be simpler to ask the user to normalize the final PC parameter L with the pixel size themselves? Even though the PC is then not strictly the EMsoft PC anymore.

On a side note, it was a bit of a hassle to obtain the pixel size on our (NORDIF) detectors when first starting out using EMsoft at NTNU (detaching the detector and imaging a transparent millimeter grid). Also, when reimplementing dictionary indexing in kikuchipy, we found  that we don't need the pixel size to project parts of a master pattern onto the detector.

**Comment by drowenhorst-nrl** [comment]
Agreed about that it is technically unnecessary for these purposes, I also got tired of me having to do the conversion (and 1/2 the time making a mistake).  Thus, I wanted to have a direct input of the same numbers between the two platforms.  Trying to think of the context where someone is using the EMsoft PC convention, but not have the four numbers? 

I have to think about it some, but another option would be to detect if the user has set EMsoft, but only specified three numbers, we can then assumed that the third number is normalize.

**Comment by hakonanes** [comment]
> Thus, I wanted to have a direct input of the same numbers between the two platforms.

I understand, this is a good argument for keeping it as is.

I'm OK with closing this issue after we inform about this requirement in the docstrings of the user facing functions accepting the `PC` parameter, and add a couple of tests. Will see if I can do this within the next weeks.
