### ISSUE TITLE
Optimize PC with `batch=True`

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#33]
@drowenhorst-nrl, how is your pattern array shaped when you use `batch=True`?

I'm passing a pattern array of shape (20, 60, 60) with 20 patterns of (60, 60) pixels to `pcopt.optimize(..., batch=True)`, and get the following error:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      1 pc0 = (0.4, 0.2, 0.5)
----> 2 pc = pcopt.optimize(s.data[tuple(idx_2d)].reshape(-1, *sig_shape), indexer, pc0, batch=True)
      3 print(pc)

File ~/kode/pyebsdindex/pyebsdindex/pcopt.py:114, in optimize(pats, indexer, PC0, batch)
    112     PCoutRet = np.zeros((npoints, 3))
    113     for i in range(npoints):
--> 114         PCopt = opt.minimize(optfunction, PC0, args=(indexer, banddat[i, :, :]), method='Nelder-Mead')
    115         PCoutRet[i, :] = PCopt['x']
    117 if emsoftflag == True: # return original state for indexer

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

The output shape of `banddat` is (20, 9), which explains the initial error. Trying to pass `banddat[i, :]` to `opt.minimize()` throws another error though...

**Comment by drowenhorst-nrl** [comment]
You are doing it perfectly fine, this was an error in the code after we changed the returns from find bands I think. 
#34 Should have fixed this issue.

**Comment by hakonanes** [comment]
That PR fixed it, thanks!
