### ISSUE TITLE
Current stable release on PyPI is still 0.1.1

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#46]
The following installs version 0.1.1: `pip install -U pyebsdindex`. This is because the [latest release on PyPI](https://pypi.org/project/pyebsdindex/#history) has version 0.2.dev0, which pip ignores unless told otherwise (can't remember the necessary flag).

There are two options to remedy this:
1. Change the `__version__` in `__init__.py` from 0.2.dev0 to 0.1.2 (and update the changelog), delete the current v0.1.2 release tag, and re-create and publish the tagged release pointing to `main`, now with the version 0.1.2.
2. Leave 0.1.2 behind and just do as in 1. but using version 0.1.3.

**Comment by hakonanes** [comment]
The above command now installs 0.1.2, great!

**Comment by drowenhorst-nrl** [comment]
I can set main back to 0.2.dev0 -- right?

**Comment by hakonanes** [comment]
Yes, reverting to 0.2.dev0 is normal procedure.
