### ISSUE TITLE
Using "Trusted publisher" publishing to PyPI fails

### ISSUE THREAD

**Issue by hakonanes** [USNavalResearchLaboratory/PyEBSDIndex#48]
Publishing to PyPI fails: https://github.com/USNavalResearchLaboratory/PyEBSDIndex/actions/runs/5800832452/job/15723768033#step:7:21

The project's publisher is apparently not configured on PyPI. This release workflow has worked for other projects I maintain, such as kikuchipy, without this. So I'm not sure why it fails now.

A trusted publisher can be configured on PyPI using this guide: https://docs.pypi.org/trusted-publishers/adding-a-publisher/. The fields should be as follows:
* Owner: USNavalResearchLaboratory
* Repository name: PyEBSDIndex
* Workflow name: publish.yml
* Environment name: leave blank

After this is done, we can re-run the publish workflow from the "Actions" tab and it should work.

**Comment by hakonanes** [comment]
This should also be done on TestPyPI.

**Comment by hakonanes** [comment]
Great, we got past this hurdle. But, alas, we forgot to remove dev from `__version__`. Upload failed because there already is. 0.2.dev0 release on PyPI because we forgot this before releasing 0.1.2 as well.

The same options as for 0.1.2 applies: https://github.com/USNavalResearchLaboratory/PyEBSDIndex/issues/46#issue-1710442568

**Comment by drowenhorst-nrl** [comment]
Yep - fixing that now.

**Comment by drowenhorst-nrl** [comment]
Ugh - and forgot needed to delete the old tag.  Third time is the charm?

**Comment by hakonanes** [comment]
Third time was the charm!

The stable (0.2.0) and latest (main branch) docs are now updated: https://pyebsdindex.readthedocs.io/en/stable/tutorials/ebsd_index_demo.html.

I'm waiting for tests to pass before releasing 0.2.0 on conda-forge: https://github.com/conda-forge/pyebsdindex-feedstock/pull/7

**Comment by hakonanes** [comment]
0.2.0 is now available from conda-forge without the now unnecessary dependency on pyswarms.
