### ISSUE TITLE
Missing dependency for distributed indexing

### ISSUE THREAD

**Issue by atpolonsky** [USNavalResearchLaboratory/PyEBSDIndex#69]
Needed to install the async-timeout package to run ebsd_index.index_pats_distributed().

Some details on the error below:

import ray.dashboard.modules.test.test_utils as test_utils
File ..."\site-packages\ray\dashboard\modules\test\test_utils.py", line 3, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'

Shortened the path to virtual environment above, but this looks like it is being caused by the ray package.
I pip installed async-timeout (pulled version 4.0.3) into the environment and it resolved this issue

Error arose on a windows 11 machine for reference.

**Comment by drowenhorst-nrl** [comment]
hmm - I am blaming the rest of the world ... that sounds like a ray dependency issue.  
Can you provide some insight on how pyebsdindex was installed?  Conda environment?  Recent release >= 0.3.6 will use the conda distribution for ray-default, and should not require a separate pip install.

**Comment by atpolonsky** [comment]
conda environment but yes I was quite behind on my version of ray, looks like conda's default ray is 2.37 now. resolved.
